spring.application.name=backend


server.port=${PORT:8080}

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pathfinder_osm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# CORS для Angular
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

osm.cache.enabled=true